# Edit this file to change the bot behavior.
# ** After editing this file, don’t forget to run `/reload-config` command! **

[nameChecker]
  patterns = [
    { regexp = "examplebadname" },
    { regexp = "kaogeek" },
    { regexp = "ก้าวgeek" },
    { regexp = "ควย" },
    { regexp = "@everyone" },
    # Zalgo Text Thanks narze [\u0300-\u036F]
    # { regexp = "[\u0300-\u036F]" },
  ]
  # ตัวเลือกเปิดปิดใช้งานเช็กตัวอักษร Zalog
  zalgoEnabled = true
  reportChannelId = "1108478073998938163"

[nameCleansing]
  enabled = true
  enabledCheckZalgo = true
  enabledCheckDehoisted = false
  enabledCheckExclamationMark = true
  enabledCheckBadName = true

[nominations]
  enabledRoles = [
    # Contributor
    { roleId = "1108437362473697370", nominationsChannelId = "1108439224413343784" },
  ]

[preventEmojiSpam]
  # ตั้งค่า Default
  #   false - อนุญาตให้ส่งข้อความที่เป็น Emoji อย่างเดียวได้
  #   true - ลบข้อความที่เป็น Emoji อย่างเดียวทิ้ง
  enabled = false

  # ลบข้อความที่เป็น Emoji อย่างเดียวทิ้ง สำหรับ Channel ต่อไปนี้
  enabledChannels = [
    # เวทีกลาง
    "1108006100101517393",
    # sandbox
    "1108600154514276395",
    # help onboard
    "1112295714001784832",
  ]

  # อนุญาตให้ส่งข้อความที่เป็น Emoji อย่างเดียวได้ สำหรับ Channel ต่อไปนี้
  disabledChannels = [
  ]

  # อนุญาตให้ Roles ต่อไปนี้ส่งข้อความที่เป็น Emoji อย่างเดียวได้
  bypassRoles = [
  # Bypass Role
  "1108774890212958269",
  # Role Contributor 
  "1108437362473697370",
  ]
