# Edit this file to change the bot behavior.
# ** After editing this file, don’t forget to run `/reload-config` command! **

[nameChecker]
  patterns = [
    { regexp = "examplebadname" },
    { regexp = "kaogeek" },
    { regexp = "ก้าวgeek" },
    { regexp = "ควย" }
  ]
  reportChannelId = "1108478073998938163"

[nominations]
  enabledRoles = [
    # Contributor
    { roleId = "1108437362473697370", nominationsChannelId = "1108439224413343784" },
  ]

[preventEmojiSpam]
  enabled = false
