name: Generate Announcement
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - run: |
          # Use GitHub CLI to create a discussion with GraphQL
          # https://docs.github.com/en/graphql/reference/mutations#creatediscussion
          gh api graphql -f query='
          mutation($input: CreateDiscussionInput!) {
            createDiscussion(input: $input) {
              discussion {
                url
              }
            }
          }' -f input='{
            "repositoryId": "R_kgDOJjuSKA",
            "title": "…",
            "body": "…",
            "categoryId": "DIC_kwDOJjuSKM4CWhXV"
          }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
