name: Generate Announcement
on:
  workflow_dispatch:
  push:
    branches:
      - discussion-generator
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - run: |
          # Use GitHub CLI to create a discussion with GraphQL
          # https://docs.github.com/en/graphql/reference/mutations#creatediscussion
          gh api graphql -f query='
          mutation {
            createDiscussion(input: {
              repositoryId: "R_kgDOJjuSKA",
              title: "…",
              body: "…",
              categoryId: "DIC_kwDOJjuSKM4CWhXV"
            }) {
              discussion {
                url
              }
            }
          }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
